title: Four Three Three
email: safog111@gmail.com
description: >-
  A blog on football analytics
baseurl: ""
url: "https://www.fourthreethree.co.uk"
twitter_username: safog111
github_username:  safog111

# Build settings
remote_theme: jekyll/minima
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
